#!/bin/bash

readonly HELP="""
Show vpn status [polybar module]
Usage: vpn_status [PARAM]
  --normal 
  --polybar 
"""
machine_name=$(/bin/cat /tmp/name | awk '{print $1}')
ip_address=$(/bin/cat /tmp/target | awk '{print $1}')
 
_polybar(){
if [ $ip_address ] && [ $machine_name ]; then
    echo "%{F#e51d0b}󰯐 %{F#ffffff}  $machine_name%{u-} - $ip_address"
else
    echo "%{F#e51d0b}󰓾 %{u-}%{F#ffffff} No target"
fi
}

_normal(){
  /bin/cat /tmp/target | grep -oP "\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}"
}

while [[ "${1}" ]]; do
  case "${1}" in 
    --polybar) _polybar; shift ;;
    --normal) _normal; shift; ;;
    --help) echo "${HELP}"; exit 0; shift ;;
    *) _polybar; shift;; 
  esac 
done

