#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc rule -a Caja state=floating follow=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
cleartarget
# Prove Video Wallpaper
#/usr/local/bin/back4.sh 0.010 ~/Pictures/rick.gif &
/usr/bin/feh --bg-fill ~/Pictures/s4vitar.png
~/.config/polybar/launch.sh 
/usr/local/bin/picom --config ~/.config/picom/picom.conf
/usr/bin/bspc config focus_follows_pointer true
/usr/local/bin/picom --experimental-backends &
# Fix Burpsuite
/usr/bin/wmname LG3D &    
/usr/bin/bspc config border_width 0
/usr/bin/xsetroot -cursor_name left_ptr &

